modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Kitoglav/BjorkHorse-ForgeFabric/issues"
license = "Apache License 2.0"

[[mods]]
modId = "bjorkhorse"
version = "${version}"
displayName = "BjorkHorse"
authors = "Kitoglav"
description = '''
Makes all horses WISE and gives them ability of TOTAL AND ABSOLUTE AGREEMENT
'''
#logoFile = ""

[[dependencies.bjorkhorse]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bjorkhorse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bjorkhorse]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
