modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Kitoglav/BjorkHorse-ForgeFabric/issues"
license = "Apache License 2.0"

[[mods]]
modId = "bjorkhorse"
version = "${version}"
displayName = "Bjork Horse"
authors = "Kitoglav"
description = '''
Makes all horses WISE and gives them ability of TOTAL AND ABSOLUTE AGREEMENT
'''
#logoFile = ""
[[dependencies.bjorkhorse]]
modId = "minecraft"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bjorkhorse]]
modId = "architectury"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"


[[mixins]]
config = "bjorkhorse.mixins.json"
